---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Robust statistical inferences using the bootstrap (PSYCH4091)

## Description

The bootstrap is a statistical method that uses data-driven simulations to make inferences.
This course provides a general and practical introduction to the bootstrap, with very little mathematics.
Examples include applications to popular psychological inference problems.

## Aims

The aim of this course is to introduce students to the bootstrap and how it can be used to make statistical inferences.
The course teaches practical R skills including how to run simulations, implement the bootstrap, illustrate results in ggplot2 and make reproducible reports using Rmarkdown. Practical applications include inferences about group comparisons and correlation analyses.

## ILOs (intended learning outcomes)

By the end of this course students will be able to:

-	Explain the goal and implementation of the percentile bootstrap at an abstract level.
-	Interact with and write R code implementing the percentile bootstrap.
-	Apply the bootstrap to inferences on measures of central tendency and correlations.
-	Illustrate raw data and bootstrap results using ggplot2.
-	Use the percentile bootstrap to make statistical inferences and interpret the results, including the description of p values and confidence intervals.
-	Write reproducible reports using RMarkdown.

The slides for all sessions are hosted on [Moodle](https://moodle.gla.ac.uk/login/index.php). They will be available on [figshare]() later on for external users.

<button type="button" class="btn btn-success btn-lg btn-block font-weight-bold">Class 1</button>

## Lecture 1: Introduction

ILOs = to be able to:  

- Define P values and confidence intervals.  
- Explain in general terms the importance of robust estimation.  
- Justify the need for detailed graphical representations.

[Notebook](nb1.html)  

Activity: dice  

## Lecture 2: The percentile bootstrap

ILOs: 

- Explain the philosophy of the percentile bootstrap.  
- Describe how the bootstrap can be implemented in R.  
- Use the bootstrap to make inferences.

[Notebook](nb2.html)

Activity: poker chips

[Interactive demo](https://seeing-theory.brown.edu/frequentist-inference/index.html#section2)

<button type="button" class="btn btn-success btn-lg btn-block font-weight-bold">Class 2</button>

## Lecture 3: Robust estimation

ILOs: 

- Describe distributions by referring to their skewness, kurtosis and the presence of outliers.  
- Explain why we need robust estimators.  
- Define trimmed means and explain their advantages.  
- Explain the imapct of outliers and skewness on estimation and statistical inferences.  
- Describe why classic outlier detection methods are not robust and the foundation of alternative robust methods.  
- Use R functions to detect outliers.  
- Use R to perform inferential statistics on the median and on trimmed means.

[Notebook](nb3.html)

Activity: dice

## Lecture 4: Sampling distributions

ILOs: 

- Define sampling distribution and standard error.  
- Given a population, compute and illustrate a sampling distribution in R.  
- Decribe the relationship between sampling distributions and bootstrap distributions.  
- Explain the usefulness of simulating sampling distributions.

[Notebook](nb4.html)

<button type="button" class="btn btn-success btn-lg btn-block font-weight-bold">Class 3</button>

## Lecture 5: Bootstrap-t

ILOs:  

- Explain the bootstrap-t and its implementation.  
- In R, use functions implementing the bootstrap-t for one group, two independent groups and two dependent groups.  

[Notebook](nb5.html)

Activities: dice, faux fish

## Lecture 6: Correlation

ILOs: 

- Describe some of the critical problems with Pearson's correlation.  
- Explain how the percentile bootstrap can be used to compute confidence intervals for a correlation coefficient and the difference between two correlation coefficients.  
- In R, use bootstrap functions to make inferences about correlation coefficients.  

[Notebook](nbk6.html)

<button type="button" class="btn btn-success btn-lg btn-block font-weight-bold">Class 4</button>

## Lecture 7: Perspectives on group comparisons

ILOs:  

- Describe different questions that we can ask about two dependent groups and two independent groups.  
- In R, illustrate observations from two dependent groups and two independent groups to address these different questions.  
- Use the percentile bootstrap to perform statistical inferences matching these different perspectives.

[Notebook](nb7.html)

Activity: dice

## Lecture 8: Shift function

ILOs:

- Discuss how continuous skewed distributions can differ.  
- Explain the shift function and interpret it for different patterns of results.  
- Use the `rogme` package to compute and illustrate shift functions.

[Notebook](nb8.html)

<button type="button" class="btn btn-success btn-lg btn-block font-weight-bold">Class 5</button>

## Lecture 9: Performance assessment

ILOs: 

- Define false positives, true positives and confidence interval probability coverage.  
- Using R, implement simulations to quantify probabilities associated with these quantities for a statistical test.
- Explain how the number of bootstrap samples can be validated for a particular approach and why it's important.

[Notebook](nb9.html)

## Lecture 10: Hierarchical bootstrap

This lecture is divided in 3 parts:  
- Hierarchical bootstrap.  
- Discussion of the dice exercise.  
- General Q&A.

ILOs: 

- Explain the basic principles of the hierarchical bootstrap and examples of applications.  
- Contrast sampling with and without replacement and from finite and infinite populations.  

No notebook for lecture 10! To see the implementation of the hierarchical bootstrap presented in class, see this [bootstrap tutorial](https://psyarxiv.com/h8ft7/), and the associated notebook `2depgps.Rmd`. For an implementation without loops, see this more elaborate [example](https://www.r-bloggers.com/resampling-hierarchically-structured-data-recursively/). 


